### ISSUE TITLE
Woeusb not working under arch linux

### ISSUE THREAD

**Issue by TheArchKnight** [WoeUSB/WoeUSB-ng#55]
I installed woeusb-ng from the AUR, and when i tried to run it on a terminal i get this error message:
```
Traceback (most recent call last):
  File "/usr/bin/woeusbgui", line 33, in <module>
    import WoeUSB.gui
  File "/usr/lib/python3.9/site-packages/WoeUSB/__init__.py", line 1, in <module>
    from WoeUSB import \
  File "/usr/lib/python3.9/site-packages/WoeUSB/core.py", line 15, in <module>
    import WoeUSB.utils as utils
  File "/usr/lib/python3.9/site-packages/WoeUSB/utils.py", line 9, in <module>
    import WoeUSB.miscellaneous as miscellaneous
  File "/usr/lib/python3.9/site-packages/WoeUSB/miscellaneous.py", line 7, in <module>
    translation = gettext.translation("woeusb", os.path.dirname(__file__) + "/locale", [locale.getlocale()[0]], fallback=True)
  File "/usr/lib/python3.9/gettext.py", line 587, in translation
    mofiles = find(domain, localedir, languages, all=True)
  File "/usr/lib/python3.9/gettext.py", line 558, in find
    for nelang in _expand_lang(lang):
  File "/usr/lib/python3.9/gettext.py", line 213, in _expand_lang
    loc = locale.normalize(loc)
  File "/usr/lib/python3.9/locale.py", line 403, in normalize
    code = localename.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

I've updated my whole system, and also reinstalled the package after doing a full removal of it

**Comment by WaxyMocha** [comment]
it works for me

**Comment by tstromberg** [comment]
FWIW, I ran into this with woeusb 0.2.10 and a fairly new ArchLinux install (EndeavourOS):

```shell
% doas woeusb --device=xxx/dev/sda --target-filesystem ntfs
doas (t@neuromancer) password: 
Traceback (most recent call last):
  File "/bin/woeusb", line 25, in <module>
    import WoeUSB.core
  File "/usr/lib/python3.10/site-packages/WoeUSB/__init__.py", line 1, in <module>
    from WoeUSB import \
  File "/usr/lib/python3.10/site-packages/WoeUSB/core.py", line 15, in <module>
    import WoeUSB.utils as utils
  File "/usr/lib/python3.10/site-packages/WoeUSB/utils.py", line 9, in <module>
    import WoeUSB.miscellaneous as miscellaneous
  File "/usr/lib/python3.10/site-packages/WoeUSB/miscellaneous.py", line 7, in <module>
    translation = gettext.translation("woeusb", os.path.dirname(__file__) + "/locale", [locale.getlocale()[0]], fallback=True)
  File "/usr/lib/python3.10/gettext.py", line 587, in translation
    mofiles = find(domain, localedir, languages, all=True)
  File "/usr/lib/python3.10/gettext.py", line 558, in find
    for nelang in _expand_lang(lang):
  File "/usr/lib/python3.10/gettext.py", line 213, in _expand_lang
    loc = locale.normalize(loc)
  File "/usr/lib/python3.10/locale.py", line 413, in normalize
    code = localename.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

The issue appears to be that the Python 3.10 stdlib breaks easily if the LANG variable is unset or set to an unexpected value. The `doas` utility creates a new environment that does not inherit the user's LANG. This is the workaround that worked for me:


```shell
doas env LANG=en_US.UTF-8 woeusb --device=xxx /dev/sda --target-filesystem ntfs
```
